name: OEM-GSI CI

on:
  workflow_dispatch:
    inputs:
      ROM_LINK:
        description: 'URL to ROM OTA Update ZIP'
        required: true
        default: 'https://oxygenos.oneplus.net/OnePlus7ProOxygen_21.O.07_OTA_007_all_1905120542_fc480574576b4843.zip'
      ROM_TYPE:
         description: 'ROM Name'
         default: 'OxygenOS'
jobs:
  Port:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Free Up Space & Set ENV Values
        id: date
        run: |
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            docker rmi `docker images -q`
            sudo apt-get remove aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
            sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* 
            sudo -E apt-get clean
            sudo -E apt-get -qq update
            echo "::set-output name=today::$(date +"%d-%m-%y")"
            
      - name: Install ErfanGSI
        run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git && cd ErfanGSIs && bash setup.sh

      - name: Start Porting
        run: cd ErfanGSIs && sudo ./url2GSI.sh "${{ github.event.inputs.ROM_LINK }}" "${{ github.event.inputs.ROM_TYPE }}"

      - name: Upload Release
        if: always()
        uses: softprops/action-gh-release@v1
        with:
          files: /home/runner/work/ErfanGSI-CI/ErfanGSI-CI/ErfanGSIs/output/*.img
          tag_name: ${{ github.run_id }}
          body: ${{ github.event.inputs.ROM_TYPE }} GSI - Ported on ${{ steps.date.outputs.today }}
